using System;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.SyncOverAsync;
using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;
using ExampleKafka.Avro;

namespace ExampleKafka
{
    /// <summary>
    /// Avro alternative to JsonSchemaProducer.cs. Transaction is generated by avrogen
    /// from value.avsc (schema-first -- the .avsc is the source of truth, unlike the
    /// JSON path where the C# class is the source of truth). Delivery-handler callback
    /// style (non-blocking, best throughput); swap to await ProduceAsync(...) the same
    /// way JsonSchemaProducerSync.cs does if per-record confirmation is preferred, and
    /// stop wrapping the serializer with .AsSyncOverAsync() if you do.
    /// </summary>
    public static class AvroProducer
    {
        public static async Task Main()
        {
            var env = KafkaConfig.LoadEnv();
            var producerConfig = KafkaConfig.BaseProducerConfig(env);
            var topic = KafkaConfig.Get(env, "TOPIC", "demo-topic");

            var adminConfig = KafkaConfig.BaseAdminConfig(env);
            if (!KafkaConfig.VerifyKafkaSetup(adminConfig, topic))
            {
                throw new InvalidOperationException("Failed to verify Kafka setup");
            }

            var srUrl = KafkaConfig.Get(env, "SCHEMA_REGISTRY_URL");
            var srKey = KafkaConfig.Get(env, "SR_API_KEY");
            var srSecret = KafkaConfig.Get(env, "SR_API_SECRET");
            if (!await KafkaConfig.VerifySchemaRegistryAsync(srUrl, srKey, srSecret))
            {
                throw new InvalidOperationException("Failed to connect to Schema Registry");
            }

            using var schemaRegistry = new CachedSchemaRegistryClient(KafkaConfig.SchemaRegistryConfig(env));

            // Register the schema explicitly, from the generated class's static _SCHEMA.
            var schemaId = await RegisterSchemaAsync(schemaRegistry, $"{topic}-value", Transaction._SCHEMA.ToString());
            Console.WriteLine($"Registered schema id: {schemaId}");

            var serializerConfig = new AvroSerializerConfig
            {
                AutoRegisterSchemas = false,
                UseLatestVersion = true,
            };
            var serializer = new AvroSerializer<Transaction>(schemaRegistry, serializerConfig);

            using var producer = new ProducerBuilder<string, Transaction>(producerConfig)
                .SetValueSerializer(serializer.AsSyncOverAsync())
                .Build();

            // avrogen keeps the .avsc field casing verbatim -- these are camelCase properties
            // (transactionId, amount, ...), NOT PascalCase, even though C# convention is PascalCase.
            var sample = new Transaction
            {
                transactionId = "txn-1",
                amount = 42.50,
                currency = "USD",
                timestamp = DateTime.UtcNow.ToString("O"),
                status = Status.completed,
            };

            Produce(producer, topic, sample.transactionId, sample);
            producer.Flush(TimeSpan.FromSeconds(10));
        }

        public static void Produce(IProducer<string, Transaction> producer, string topic, string key, Transaction value)
        {
            producer.Produce(topic, new Message<string, Transaction> { Key = key, Value = value }, report =>
            {
                if (report.Error.IsError)
                {
                    Console.Error.WriteLine($"Delivery failed for key '{report.Message.Key}': {report.Error.Reason}");
                }
                else
                {
                    Console.WriteLine($"Delivered to {report.TopicPartitionOffset}");
                }
            });
        }

        public static async Task<int> RegisterSchemaAsync(ISchemaRegistryClient schemaRegistry, string subject, string schemaJson)
        {
            var schema = new Schema(schemaJson, SchemaType.Avro);
            return await schemaRegistry.RegisterSchemaAsync(subject, schema);
        }
    }
}
